[[pages]]
path = "./processor.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "./myapp.py"
name = "Home2"
icon = "ğŸ "

[[pages]]
path = "./logs.py"
name = "Logs"
icon = ":books:"
url_path = "my_books" # You can override the default url path for a page